FROM python:3.12

WORKDIR /Prototyp_1

COPY requirements.txt .

COPY Prototyp_1 Prototyp_1

COPY config.ini config.ini

RUN pip install -r requirements.txt

CMD [ "python", "Prototyp_1/__init__.py" ]
