version: '3.8'

services:
  app:
    build: /Prototyp_2
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: factory
      MYSQL_DB: db_v1
      FLASK_SECRET_KEY: f@ctory
      DEBUG: True
      FLASK_RUN_HOST: 0.0.0.0
      UPLOAD_FOLDER: /app/Static/product_pictures  # Updated picture path
    volumes:
      - picture-volume:/app/Static/product_pictures  # Mounting a volume for storing pictures
    networks:
      - mynetwork

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: factory
      MYSQL_DATABASE: db_v1
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3309:3306"
    networks:
      - mynetwork

volumes:
  db-data:
  picture-volume:  # Define a volume for storing pictures

networks:
  mynetwork:
